"""empty message

Revision ID: 2303e2ad9738
Revises: 355319b64a3f
Create Date: 2020-03-22 20:50:43.161345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2303e2ad9738'
down_revision = '355319b64a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'CEN', ['uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'CEN', type_='unique')
    # ### end Alembic commands ###
