"""empty message

Revision ID: 355319b64a3f
Revises: 
Create Date: 2020-03-21 19:42:34.045309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355319b64a3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CEN',
    sa.Column('uuid', sa.String(length=16), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CEN')
    # ### end Alembic commands ###
