"""empty message

Revision ID: f4f463dda3e8
Revises: 2303e2ad9738
Create Date: 2020-03-22 20:58:31.625457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4f463dda3e8'
down_revision = '2303e2ad9738'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CEN', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('CEN', sa.Column('publsihed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.create_unique_constraint(None, 'CEN', ['uuid'])
    op.drop_column('CEN', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CEN', sa.Column('created', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'CEN', type_='unique')
    op.drop_column('CEN', 'publsihed_at')
    op.drop_column('CEN', 'created_at')
    # ### end Alembic commands ###
